spring.application.name=pulsedesk

spring.datasource.url=jdbc:h2:mem:pulsedesk
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

huggingface.api.token=
huggingface.api.model=meta-llama/Meta-Llama-3-8B-Instruct
